cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns =[
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from myshop import views


urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='shop:main_page',
        permanent=False)),
    url(r'^admin/', include(admin.site.urls)),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^pincodes/', include('pincodes.urls', namespace='pincodes')),
    url(r'^testimonial/', include('testimonials.urls',
        namespace='testimonials')),
    url(r'^maps/', include('storemaps.urls', namespace='maps')),
    url(r'^search/', include('haystack.urls')),
    url(r'^register/$', views.register, name='register'),
    url(r'^djrichtextfield/', include('djrichtextfield.urls'))


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

shop/urls.py
from django.conf.urls import url
from shop import views


urlpatterns = [
    url(r'^$', views.mainPage, name='main_page'),
    url(r'^search/$', views.search, name="search"),
    url(r'^product/$', views.product_list, name='product_list'),
    url(r'^pincode/(?P<id>\d+)/', views.pincode_availaiblity, name='pincode_availaiblity'),
    url(r'^termsandconditions/$', views.termsandconditions, name='terms_and_conditions'),
    url(r'^privacypolicy/$', views.privacypolicy, name='privacy_policy'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.category_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),

]

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.contrib.postgres.fields import JSONField
import re
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.html import mark_safe
from djrichtextfield.models import RichTextField
# Create your models here.


class Cateogry(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(db_index=True, unique=True)
    parent_cateogry = models.ForeignKey('self', blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'cateogry'
        verbose_name_plural = 'cateogries'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_cateogry', args=[self.slug])

    def save(self, *args, **kwargs):
        for field_name in ['name', ]:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(Cateogry, self).save(*args, **kwargs)


class Product(models.Model):
    cateogry = models.ForeignKey('Cateogry', related_name='products')
    parent_product = models.ForeignKey('self', blank=True, null=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True,
                                blank=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    features = JSONField(blank=True, null=True)


    class Meta:
        ordering = ['created']
        index_together = [('id', 'slug')]

    def __str__(self):
        return self.name

    def option_value(self):
        if self.parent_product:
            pattern = '(?<=\()(.*?)(?=\))'
            return re.search(pattern, self.name).group()

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def clean(self, *args, **kwargs):
        if self.parent_product:
            if not self.price:
                raise ValidationError('Price field cannot be empty')
        super().clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)



# Create your models here.
class ModifiedCategory(MPTTModel):
    name = models.CharField(max_length=200, unique=True, db_index=True)
    slug = models.SlugField(db_index=True, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='children', db_index=True)
    description = RichTextField(blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        ordering = ['name']
        verbose_name = 'modified category'
        verbose_name_plural = 'modified categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def save(self, *args, **kwargs):
        for field_name in ['name', ]:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super().save(*args, **kwargs)

    def get_description(self):
        try:
            if self.description:
                return self.description
            else:
                return self.parent.get_description()
        except:
            pass

    def name_for_hierarchial_list(self):
        try:
            pattern = '(?<=\()(.*?)(?=\))'
            return re.findall(pattern, self.name)[-1].capitalize()
        except:
            return self.name



class ModifiedProduct(MPTTModel):
    name = models.CharField(max_length=200, unique=True, db_index=True)
    category = models.ForeignKey(ModifiedCategory,
                                 related_name='category')
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='children', db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = RichTextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    features = JSONField(blank=True, null=True)
    option_type = models.CharField(max_length=20, blank=True)
    visible = models.BooleanField(default=True)
    is_unique = models.BooleanField(default=True)
    optional_visible_name = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.category.name + " " + self.name

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        ordering = ['created']
        index_together = [('id', 'slug')]

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


    def get_features(self):
        try:
            if self.features:
                return self.features
            else:
                return self.parent.get_features()
        except:
            pass

    def get_images(self):
        try:
            if self.product.all():
                return self.product.all()
            else:
                return self.parent.get_images()
        except:
            pass


    def get_description(self):
        try:
            if self.description:
                return self.description
            else:
                return self.parent.get_description()
        except:
            pass

    def get_option_name(self):
        try:
            pattern = '(?<=\()(.*?)(?=\))'
            return re.findall(pattern, self.name)[-1]
        except:
            pass

    def name_for_hierarchial_list(self):
        try:
            pattern = '(?<=\()(.*?)(?=\))'
            return re.findall(pattern, self.name)[-1]
        except:
            return self.name

    def get_options(self):
        options = self.get_ancestors().exclude(level=0)
        return options


    def get_breadcrums(self):
        list = [m for m in self.category.get_ancestors()] + [self.category] + [m for m in self.get_ancestors()] + [self]
        return list

class ProductImages(models.Model):
    image = models.ImageField(upload_to="modifiedproducts/images/%Y/%m/%d",
                              blank=True)
    product = models.ForeignKey(ModifiedProduct,
                                related_name="product")

    class Meta:
        verbose_name = 'images related with products'
        verbose_name_plural = 'Product Images'


    def __str__(self):
        return self.image.name

    def image_tag(self):
            return mark_safe('<img src="%s" width="150" height="150" />' % (self.image.url))

shop/forms.py
from django import forms

class PincodeForm(forms.Form):
    pincode = forms.IntegerField(label='Your Pincode', min_value=0)

shop/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.db.models import Q
import operator
from functools import reduce
from shop.models import ModifiedCategory, ModifiedProduct
from cart.forms import CartAddProductForm
from testimonials.models import Testimonial_
import requests
import json
from shop.forms import PincodeForm
from cart.views import check_availability

from django.http import JsonResponse


# Create your views here.
def mainPage(request):
    first_testimonial = Testimonial_.objects.first()
    testimonials = Testimonial_.objects.all()
    return render(request, 'shop/product/main.html',
                  {'testimonials': testimonials,
                   'first_testimonial': first_testimonial, })


def product_list(request, category_slug=None):
    category = None
    products = ModifiedProduct.objects.filter(level=0)
    if category_slug:
        category = get_object_or_404(ModifiedCategory, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'products': products,
    })


def category_list(request, category_slug=None):
    category = get_object_or_404(ModifiedCategory, slug=category_slug).get_leafnodes()
    if not category:
        category = get_list_or_404(ModifiedCategory, slug=category_slug)
    else:
        category = get_object_or_404(ModifiedCategory, slug=category_slug).get_leafnodes()

    products = ModifiedProduct.objects.filter(category__in=category).filter(is_unique=True)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'products': products,
    })


def product_detail(request, id, slug):
    pincode_form = PincodeForm()
    product = get_object_or_404(ModifiedProduct, id=id,
                                slug=slug,
                                available=True)
    if product.is_root_node():
        child_products = product.get_children()
    else:
        child_products = product.parent.get_children()
    if product.get_children():
        return redirect(product.get_children()[0])
    else:
        cart_product_form = CartAddProductForm()

        if request.is_ajax():
            template = 'partial-results.html'
        else:
            template = 'shop/product/detail.html'
        return render(request, template,
                      {'product': product,
                       'cart_product_form': cart_product_form,
                       'child_products': child_products,
                       'pincode_form':pincode_form,
                       })

def termsandconditions(request):
    return render(request, 'shop/static_templates/termsandconditions.html')

def privacypolicy(request):
    return render(request, 'shop/static_templates/privacypolicy.html')


def pincode_availaiblity(request, id):
    pincode = request.GET.get('pincode', None)
    availability_details = check_availability(int(pincode), int(id))

    if availability_details['pincode_details']:
        is_valid_Pincode = True
        office = availability_details['pincode_details'][0].officeName
        district = availability_details['pincode_details'][0].districtName
        if availability_details['availability']:
            is_available = True
        else:
            is_available = False
    else:
        office = None
        district = None
        is_valid_Pincode = False
        is_available = False
    data = {
            'is_valid_Pincode': is_valid_Pincode,
            'is_available': is_available,
            'office': office,
            'district': district,
    }
    #
    # # address = "https://pincode.saratchandra.in/api/pincode/" + str(pincode)
    request.session['pincode'] = str(pincode)
    # response = requests.get(address)
    # json_data = json.loads(response.text)
    return JsonResponse(data)


def search(request):
    query_string = ''
    found_entries = None

    if (request.GET.get('q')) and request.GET.get('q').strip():
        values = request.GET.get('q').split()
        query_string = request.GET.get('q')
        products = ModifiedProduct.objects.filter(reduce(operator.or_,(Q(name__icontains=x) for
        x in values))).filter(is_unique=True)
        return render(request, 'shop/product/list.html',{'products': products, 'query_string':query_string})

    else:
        products = ModifiedProduct.objects.all().filter(is_unique=True)
        return render(request, 'shop/product/list.html',{'products': products})

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {{   product.cateogry }} | {{ product.name }}
{#    {% if cateogry %}#}
{#        {{ cateogry.title }}#}
{#    {% else %}#}
{#        Products#}
{#    {% endif %}#}
{% endblock %}
{% block carousel %}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/more_detail.css' %}">
{% include "shop/product/more_detail.html" %}
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    {% if cateogry %}
        Kaarabazaar|{{ cateogry.name }}
    {% else %}
        Kaarabazaar|Products
    {% endif %}
{% endblock %}

{% block sidebar %}
{% include "shop/sidebar.html" %}
{% endblock sidebar %}

{% block carousel %}
<link rel="stylesheet" href="{% static 'css/product_list.css' %}">
<div class="col-sm-6 col-md-9" style="padding-top: 30px;">
      {% if query_string %}<p>You searched for "<em><strong>{{query_string}}</strong></em>"</p>
      {% else %} {% endif %}
      {% if not products %}<p> Your search didn't produce any results. Please hover over products to see category-wise
        products </p> {% endif %}
     <div class="row flex" >
         {% for product in products %}
         <div class="col-md-3" >
             <div class="thumbnail" >
                 <div><a href="{{ product.get_absolute_url }}">
                   {% if product.get_images %}
                   {% load thumbnail %}
                   {% thumbnail product.get_images.0.image "120" as im %}
                   <a href="{{ product.get_absolute_url }}">
                     <img class="center-block img-responsive " src="{% if im %}{{ im.url }}
                     {% else %}{% static "img/no_image.png" %}{% endif %}" alt="..."
                     >
                   </a>
                   {% endthumbnail %}
                   {% else %}
                   <a href="{{ product.get_absolute_url }}">
                     <img class="center-block img-responsive " src="{% static "img/no_image.png" %}" alt="..."
                     >
                   </a>
                   {% endif %}
                 </div>
   <div class="caption text-center">
     <a href="{{product.get_absolute_url}}"><p>{% if product.optional_visible_name %}{{product.optional_visible_name}} {% else %}{{ product.name }}{% endif %}</p></a>
     <p><span class="WebRupee">Rs</span> {{ product.price }}</p>
   </div>
 </div>
</div>
{% endfor %}
</div>
</div>

{% for e in found_entries  %}
  {{e}}
{% endfor %}
{% endblock %}

shop/templates/shop/product/main.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
   Pahal Store
{% endblock %}

{% block sidebar %}
{% include "shop/sidebar.html" %}
{% endblock sidebar %}

{% block carousel %}

{% include "shop/carousel.html" %}

{% endblock %}

{% block testimonial %}

{% include "shop/main_page_testimonial.html" %}

{% endblock %}


{% block topseller %}
	{% include "shop/topseller.html" %}
{% endblock topseller %}

{% block recommendations %}
	{% include "shop/recommendation_carousel.html" %}
{% endblock recommendations %}

shop/templates/shop/product/more_detail.html
{% load static %}
{% load thumbnail %}
{% load crispy_forms_tags %}

    <div class ="container" style="padding-top: 50px" id ="products">
        <div class="row">


            <div class="col-sm-6 col-md-6" style="min-height:550px;">
            <div>
              <span class="badge-info">
              <a href="{% url 'shop:main_page' %}">Home</a> >
              {% for link in product.get_breadcrums %}
              {% if not forloop.last %}
              <a href="{{link.get_absolute_url}}">{{link.name_for_hierarchial_list}} </a> >
              {% else %}
              <a href="{{link.get_absolute_url}}">{{link.name_for_hierarchial_list}}</a>
              {% endif %}
              {% endfor %}
              </span>
            </div>


              <div class="bzoom_wrap">
                <ul id = "bzoom">
                  {% if product.get_images  %}
                  <p class="image_length" hidden>{{product.get_images|length}}</p>
                  {% for image in product.get_images %}
                  {% thumbnail image.image "400" as small_image %}
                  <li>
                    <img class="bzoom_thumb_image" src="{{small_image.url}}" alt="">
                    <img class="bzoom_big_image" src="{{image.image.url}}" alt="">
                  </li>
                  {% endthumbnail %}
                  {% endfor %}
                  {% else %}
                  <li>
                    <img class="bzoom_thumb_image" src="{% static 'img/no_image.png' %}" alt="">
                    <img class="bzoom_big_image" src="{% static 'img/no_image.png' %}" alt="">
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>

            <div class="col-sm-6 col-md-6">
              {% if messages %}
                <div class="alert alert-warning alert-dismissible" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
              </div>
            {% endif %}
                <h5>{% if product.optional_visible_name %}{{product.optional_visible_name}} {% else %}{{ product.name }}{% endif %}</h5>
                <p>
                    <div>
                    <div >
                      <a href="https://twitter.com/share" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                    </div>
                    </div>
                    <!-- Place this tag where you want the +1 button to render. -->
                </p>

                  <div class="row">
                    <div class="col-sm-6">

                <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                <p ><span class="WebRupee">Rs</span> {{ product.price }}{% if product.price < 800 %}<span class="small"> + Shipping Charges</span>{% endif %}  </p>
                <form action="{% url 'cart:cart_add' product.id %}?prev={{request.path}}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input class ="btn btn-xs btn-danger" type="submit" value="Add to Cart">
                </form>
                {% for options in product.get_options %}
                    <h6 style="padding-top:2px;">{{ options.option_type }}:</h6>
                    {% for op in options.parent.get_children %}
                      <a href="{{op.get_absolute_url}}"><span class="badge">{{op.get_option_name}}</span></a>
                    {% endfor %}
                {% endfor %}

                {% if child_products %}
                  <div class="child_options" style="padding-top:2px;">
                    <h6>{{child_products.0.option_type}}:</h6>
                   {% for product in child_products %}
                      <a href="{{product.get_absolute_url}}"><span class="badge small">{{product.get_option_name}}</span></a>
                  {% endfor %}
                  </div>
                {% endif %}
                    </div>
                    <div class="col-sm-6 nopadding" style="font-size: 11px;">
                      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js">
                      <p class="availability-col">Estimated Shipping Charges</p>
                      <p class="availability-col">{% if product.price < 800 %} <span class="WebRupee">Rs</span> 40 {% else %}You are eligible for free delivery.{% endif %}</p>
                      <a href="#" data-toggle="tooltip" data-html="true" data-placement="bottom" title="For all orders above <span class='WebRupee'>Rs.</span> 800, shipping is free. Otherwise the charges are based on the distance between our nearest serving store and the delivery address.">Read Shipping Charges Policy</a>
                      <form action="#" method="post" id ="pincodeform">
                          {% csrf_token %}
                          {{ pincode_form|crispy}}
                          <p id="product_id" hidden>{{product.id}}<p>
                          <input class="btn btn-xs btn-info" type="submit" value="Check Availablity" />
                      </form>
                      <p class="availability-col" id="available_check"></p>
                      {% if request.session.pincode %}
                        <p class="availability-col" id ="pincode">You have set your location pincode to be :<b>{{request.session.pincode}}</b></p>
                        {% else %}
                        <p class="availability-col" id="pincode"></p>
                      {% endif %}

                      <script type="text/javascript">
                        $(function () {
                          $('[data-toggle="tooltip"]').tooltip()
                        })
                      </script>
                      <script type="text/javascript">
                        $(document).on('submit', '#pincodeform', function(e){
                          e.preventDefault();
                          var pincode = $('#id_pincode').val();
                          var product_id = $('#product_id').html();
                          var pincode_url = "/shop/pincode/" + product_id +"/";
                          var set_pincode_msg_start = "You have set your location pincode to be :<b>"
                          var set_pincode_msg_end = "</b>"

                          $.ajax({
                            url: pincode_url,
                            data:{
                              'pincode':pincode,
                            },
                            dataType: 'json',
                            success: function(data){

                              if (data["is_valid_Pincode"]){
                                  if (data["is_available"]){
                                    $('#available_check').html("Product is available at " + data["office"] +" " + data["district"]);
                                    $('#pincode').html(set_pincode_msg_start + pincode + set_pincode_msg_end);
                                  } else {
                                    $('#available_check').html("Sorry ! Product is not available at " + data["office"] +" " + data["district"]);
                                    $('#pincode').html(set_pincode_msg_start + pincode + set_pincode_msg_end);
                                  }
                              }
                              else {
                                $('#available_check').html("The pincode entered by you is invalid. Please enter correct pincode.");
                                $('#pincode').html(set_pincode_msg_start + pincode + set_pincode_msg_end);
                              }
                            }
                          });

                        });
                      </script>

                    </div>
                  </div>
                {% if product.get_description %}
                <div class="success" style="font-size:14px; padding-top:15px;">
                  <h6>Product Description:</h6>

                  <p >{% autoescape off %}
                    {{ product.description|linebreaks }}
                  {% endautoescape %}</p>
                </div>
                {% endif %}
                {% if product.category.get_description %}
                <div class="success" style="font-size:14px; padding-top:15px;">
                  <h6>Category Description:</h6>

                  <p >{% autoescape off %}
                      {{ product.category.get_description|linebreaks }}
                  {% endautoescape %}</p>
                </div>
                {% endif %}
                {% if product.get_features %}
                  <div >
                    <table class = "table table-condensed" style ="font-size:12px;" id ="table_detail">
                       <caption>Features</caption>
                       <tbody>
                         {% for key, value in product.get_features.items %}
                            <tr>
                              <td>{{key}}:</td>
                              <td>{{value}}</td>
                            </tr>
                         {% endfor %}
                       </tbody>
                    </table>
                  </div>
                {% endif %}
            </div>
            <p id="city"></p>
        </div>
        <link rel="stylesheet" href="{% static 'css/bzoom.css' %}">
        <script src="{% static 'js/loadingoverlay.min.js' %}"></script>
        <script src="{% static 'js/option_selector.js' %}"></script>
        <script src="{% static 'js/jqzoom.js' %}"></script>
        <script type="text/javascript">
          $("#bzoom").zoom({
            zoom_area_width: 800,
            thumb_image_width:377.2,
            thumb_image_height:337.2,
            zoom_area_height:900,
            small_thumbs:{{product.get_images|length}},
            small_thumb_height:100,
            small_thumb_width:250,
            // MORE OPTIONS HERE
            });
        </script>
        <script type="text/javascript">
          c = $('.image_length').html();
          if (c ==1 ) {
              $('.bzoom_small_thumbs > ul > li').remove();}
        </script>
        <script type="text/javascript">
          $(".alert").alert()
        </script>
    </div>