cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns =[
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),

]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from myshop import views


urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='shop:main_page',
        permanent=False)),
    url(r'^admin/', include(admin.site.urls)),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^pincodes/', include('pincodes.urls', namespace='pincodes')),
    url(r'^testimonial/', include('testimonials.urls',
        namespace='testimonials')),
    url(r'^maps/', include('storemaps.urls', namespace='maps')),
    url(r'^search/', include('haystack.urls')),
    url(r'^register/$', views.register, name='register'),
    url(r'^djrichtextfield/', include('djrichtextfield.urls'))


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

shop/urls.py
from django.conf.urls import url
from shop import views


urlpatterns = [
    url(r'^$', views.mainPage, name='main_page'),
    url(r'^search/$', views.search, name="search"),
    url(r'^product/$', views.product_list, name='product_list'),
    url(r'^pincode/(?P<id>\d+)/', views.pincode_availaiblity, name='pincode_availaiblity'),
    url(r'^termsandconditions/$', views.termsandconditions, name='terms_and_conditions'),
    url(r'^privacypolicy/$', views.privacypolicy, name='privacy_policy'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.category_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),

]

storemaps/urls.py
from django.conf.urls import url
from storemaps import views

urlpatterns = [
    url(r'^$', views.show_map, name='show_map'),
]

testimonials/urls.py
from django.conf.urls import url
from testimonials import views


urlpatterns = [
    url(r'^$', views.read_and_write_testimonial, name='testimonial_list'),
    url(r'^selected-testimonials/$', views.selected_testimonials,
        name='selected_testimonials'),
]

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.contrib.postgres.fields import JSONField
import re
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.html import mark_safe
from djrichtextfield.models import RichTextField
# Create your models here.


class Cateogry(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(db_index=True, unique=True)
    parent_cateogry = models.ForeignKey('self', blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'cateogry'
        verbose_name_plural = 'cateogries'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_cateogry', args=[self.slug])

    def save(self, *args, **kwargs):
        for field_name in ['name', ]:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(Cateogry, self).save(*args, **kwargs)


class Product(models.Model):
    cateogry = models.ForeignKey('Cateogry', related_name='products')
    parent_product = models.ForeignKey('self', blank=True, null=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True,
                                blank=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    features = JSONField(blank=True, null=True)


    class Meta:
        ordering = ['created']
        index_together = [('id', 'slug')]

    def __str__(self):
        return self.name

    def option_value(self):
        if self.parent_product:
            pattern = '(?<=\()(.*?)(?=\))'
            return re.search(pattern, self.name).group()

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def clean(self, *args, **kwargs):
        if self.parent_product:
            if not self.price:
                raise ValidationError('Price field cannot be empty')
        super().clean(*args, **kwargs)

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)



# Create your models here.
class ModifiedCategory(MPTTModel):
    name = models.CharField(max_length=200, unique=True, db_index=True)
    slug = models.SlugField(db_index=True, unique=True)
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='children', db_index=True)
    description = RichTextField(blank=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        ordering = ['name']
        verbose_name = 'modified category'
        verbose_name_plural = 'modified categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def save(self, *args, **kwargs):
        for field_name in ['name', ]:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super().save(*args, **kwargs)

    def get_description(self):
        try:
            if self.description:
                return self.description
            else:
                return self.parent.get_description()
        except:
            pass

    def name_for_hierarchial_list(self):
        try:
            pattern = '(?<=\()(.*?)(?=\))'
            return re.findall(pattern, self.name)[-1].capitalize()
        except:
            return self.name



class ModifiedProduct(MPTTModel):
    name = models.CharField(max_length=200, unique=True, db_index=True)
    category = models.ForeignKey(ModifiedCategory,
                                 related_name='category')
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='children', db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = RichTextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    features = JSONField(blank=True, null=True)
    option_type = models.CharField(max_length=20, blank=True)
    visible = models.BooleanField(default=True)
    is_unique = models.BooleanField(default=True)
    optional_visible_name = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.category.name + " " + self.name

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        ordering = ['created']
        index_together = [('id', 'slug')]

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


    def get_features(self):
        try:
            if self.features:
                return self.features
            else:
                return self.parent.get_features()
        except:
            pass

    def get_images(self):
        try:
            if self.product.all():
                return self.product.all()
            else:
                return self.parent.get_images()
        except:
            pass


    def get_description(self):
        try:
            if self.description:
                return self.description
            else:
                return self.parent.get_description()
        except:
            pass

    def get_option_name(self):
        try:
            pattern = '(?<=\()(.*?)(?=\))'
            return re.findall(pattern, self.name)[-1]
        except:
            pass

    def name_for_hierarchial_list(self):
        try:
            pattern = '(?<=\()(.*?)(?=\))'
            return re.findall(pattern, self.name)[-1]
        except:
            return self.name

    def get_options(self):
        options = self.get_ancestors().exclude(level=0)
        return options


    def get_breadcrums(self):
        list = [m for m in self.category.get_ancestors()] + [self.category] + [m for m in self.get_ancestors()] + [self]
        return list

class ProductImages(models.Model):
    image = models.ImageField(upload_to="modifiedproducts/images/%Y/%m/%d",
                              blank=True)
    product = models.ForeignKey(ModifiedProduct,
                                related_name="product")

    class Meta:
        verbose_name = 'images related with products'
        verbose_name_plural = 'Product Images'


    def __str__(self):
        return self.image.name

    def image_tag(self):
            return mark_safe('<img src="%s" width="150" height="150" />' % (self.image.url))

shop/forms.py
from django import forms

class PincodeForm(forms.Form):
    pincode = forms.IntegerField(label='Your Pincode', min_value=0)

shop/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.db.models import Q
import operator
from functools import reduce
from shop.models import ModifiedCategory, ModifiedProduct
from cart.forms import CartAddProductForm
from testimonials.models import Testimonial_
import requests
import json
from shop.forms import PincodeForm
from cart.views import check_availability

from django.http import JsonResponse


# Create your views here.
def mainPage(request):
    first_testimonial = Testimonial_.objects.first()
    testimonials = Testimonial_.objects.all()
    return render(request, 'shop/product/main.html',
                  {'testimonials': testimonials,
                   'first_testimonial': first_testimonial, })


def product_list(request, category_slug=None):
    category = None
    products = ModifiedProduct.objects.filter(level=0)
    if category_slug:
        category = get_object_or_404(ModifiedCategory, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'products': products,
    })


def category_list(request, category_slug=None):
    category = get_object_or_404(ModifiedCategory, slug=category_slug).get_leafnodes()
    if not category:
        category = get_list_or_404(ModifiedCategory, slug=category_slug)
    else:
        category = get_object_or_404(ModifiedCategory, slug=category_slug).get_leafnodes()

    products = ModifiedProduct.objects.filter(category__in=category).filter(is_unique=True)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'products': products,
    })


def product_detail(request, id, slug):
    pincode_form = PincodeForm()
    product = get_object_or_404(ModifiedProduct, id=id,
                                slug=slug,
                                available=True)
    if product.is_root_node():
        child_products = product.get_children()
    else:
        child_products = product.parent.get_children()
    if product.get_children():
        return redirect(product.get_children()[0])
    else:
        cart_product_form = CartAddProductForm()

        if request.is_ajax():
            template = 'partial-results.html'
        else:
            template = 'shop/product/detail.html'
        return render(request, template,
                      {'product': product,
                       'cart_product_form': cart_product_form,
                       'child_products': child_products,
                       'pincode_form':pincode_form,
                       })

def termsandconditions(request):
    return render(request, 'shop/static_templates/termsandconditions.html')

def privacypolicy(request):
    return render(request, 'shop/static_templates/privacypolicy.html')


def pincode_availaiblity(request, id):
    pincode = request.GET.get('pincode', None)
    availability_details = check_availability(int(pincode), int(id))

    if availability_details['pincode_details']:
        is_valid_Pincode = True
        office = availability_details['pincode_details'][0].officeName
        district = availability_details['pincode_details'][0].districtName
        if availability_details['availability']:
            is_available = True
        else:
            is_available = False
    else:
        office = None
        district = None
        is_valid_Pincode = False
        is_available = False
    data = {
            'is_valid_Pincode': is_valid_Pincode,
            'is_available': is_available,
            'office': office,
            'district': district,
    }
    #
    # # address = "https://pincode.saratchandra.in/api/pincode/" + str(pincode)
    request.session['pincode'] = str(pincode)
    # response = requests.get(address)
    # json_data = json.loads(response.text)
    return JsonResponse(data)


def search(request):
    query_string = ''
    found_entries = None

    if (request.GET.get('q')) and request.GET.get('q').strip():
        values = request.GET.get('q').split()
        query_string = request.GET.get('q')
        products = ModifiedProduct.objects.filter(reduce(operator.or_,(Q(name__icontains=x) for
        x in values))).filter(is_unique=True)
        return render(request, 'shop/product/list.html',{'products': products, 'query_string':query_string})

    else:
        products = ModifiedProduct.objects.all().filter(is_unique=True)
        return render(request, 'shop/product/list.html',{'products': products})

shop/templates/shop/base.html
{% load static %}
{% load app_filter%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "img/pahal-logo.ico" %}">
    <title> {% block title%}
    {% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <script src="https://use.fontawesome.com/e3e69968e1.js"></script>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <!-- Bootstrap Theme -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/readable/bootstrap.min.css">
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/navbar-fixed-top.css' %}">
    <!-- css for drop down menu -->
    <link rel="stylesheet" href="{% static 'css/navbar-element.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/testimonial-sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'css/panel.css' %}">
    <link rel="stylesheet" href="{% static 'css/midview.css' %}">
    <link rel="stylesheet" href="{% static 'css/tagline.css' %}">
    <link rel="stylesheet" href="{% static 'css/top-navigation-product-list.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/WebRupee/2.0/font.min.css">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'js/carousel.js' %}"></script>
    <style>
    .nopadding {
   padding:3px; !important;

}
    body {
      font-family: 'Open Sans', sans-serif;
    }

  .content {
      padding-top: 30px;
  }

  /* Testimonials */
  .testimonials blockquote {
      background: #f8f8f8 none repeat scroll 0 0;
      border: medium none;
      color: #666;
      display: block;
      font-size: 14px;
      line-height: 20px;
      padding: 15px;
      position: relative;
  }
  .testimonials blockquote::before {
      width: 0;
      height: 0;
    right: 0;
    bottom: 0;
    content: " ";
    display: block;
    position: absolute;
      border-bottom: 20px solid #fff;
    border-right: 0 solid transparent;
    border-left: 15px solid transparent;
    border-left-style: inset; /*FF fixes*/
    border-bottom-style: inset; /*FF fixes*/
  }
  .testimonials blockquote::after {
      width: 0;
      height: 0;
      right: 0;
      bottom: 0;
      content: " ";
      display: block;
      position: absolute;
      border-style: solid;
      border-width: 20px 20px 0 0;
      border-color: #e63f0c transparent transparent transparent;
  }
  .testimonials .carousel-info img {
      border: 1px solid #f5f5f5;
      border-radius: 50px ;
      height: 25px;
      padding: 3px;
      width: 75px;
  }
  .testimonials .carousel-info {
      overflow: hidden;
  }
  .testimonials .carousel-info img {
      margin-right: 15px;
  }
  .testimonials .carousel-info span {
      display: block;
  }
  .testimonials span.testimonials-name {
      color: #e6400c;
      font-size: 16px;
      font-weight: 300;
      margin: 23px 0 7px;
  }
  .testimonials span.testimonials-post {
      color: #656565;
      font-size: 12px;
  }
.dropdown:hover .dropdown-menu {
    display: block;
    margin-top:0;
  }

  </style>

  </head>

  <body>

      <div class="container fixedTopContainer" style="z-index:99; margin-top:-70px; ">

	           <div class="col-md-12">
              <h3  class="text-center" style="font-family: 'Indie Flower', cursive; font-size: 1.15em;text-align:center; float: none;
              ">"Every rupee spent by you will be used for welfare activities in prisons"</h3>
            </div>
          </div>
       </div>

    <!-- Fixed navbar -->

    <nav class="navbar navbar-default navbar-custom navbar-fixed-top"
    style="z-index:1;">
      <div class="container" style="padding-right: 0;">

        <div class="navbar-header pull-left">
          <a class="navbar-brand" href="{% url 'shop:main_page' %}" style ="padding-left: 0;"><img style ="padding-top:25px; "class="img-responsive" src="{% static 'img/C-1 Web image.png' %}"></a>

        </div>
        <div class="navbar-header pull-right clearfix">

             <a class="navbar-brand" href="http://admis.hp.nic.in/hpprisons/" style ="padding-right:0;"><img src="{% static 'img/hpj-logo.png' %}"></a>

          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>


        </div>

        <div id="navbar" class="navbar-collapse collapse navbar-custom" >
          <ul class="nav navbar-nav" style="margin-top:37px;">
            <li><a href="{% url 'shop:main_page' %}" style="font-family: 'Oswald', sans-serif;"><span class="glyphicon glyphicon-home"></span>  Home</a></li>
            <li class="active dropdown">
              <a href="/" class="dropdown-toggle" data-toggle="dropdown" style="font-family: 'Oswald', sans-serif;">Products <span class="caret"></span></a>

                <ul class="dropdown-menu multi-column columns-3">
                  <div class="row">
                    <div class="col-sm-4">
                      <ul class="multi-column-dropdown">
                      {% include 'shop/top_navigation_bar_bakery_list.html' %}
                      </ul>
                    </div>
                    <div class="col-sm-4">
                      <ul class="multi-column-dropdown">
                        {% include 'shop/top_navigation_bar_cloth_list.html' %}
                      </ul>
                    </div>
                    <div class="col-sm-4">
                      <ul class="multi-column-dropdown">
                        {% include 'shop/top_navigation_bar_handicraft_list.html' %}
                      </ul>
                    </div>

                  </div>
                </ul>

            </li>

            <li><a href="#about" style="font-family: 'Oswald', sans-serif;">About</a></li>
            <li><a href="#contact" style="font-family: 'Oswald', sans-serif;">Contact</a></li>
            <li><a href="{% url 'maps:show_map' %}" style="font-family: 'Oswald', sans-serif;">Locate Us</a></li>





            <div class="col-md-5 pull-right">
              <div class="col-md-5 pull-right" style ="padding-top:23px;">
                {% if user.is_authenticated %}
                 <strong>{{ user.get_username }}'s</strong>
                   {% with total_items=cart|length %}
                      {% if cart|length > 0 %}
                      <span class="glyphicon glyphicon-shopping-cart"></span>:
                      <a href="{% url 'cart:cart_detail' %}" >
                      {{ total_items }} item{{ total_items|pluralize }}
                      {% else %}
                        <span class="glyphicon glyphicon-shopping-cart"></span> is empty
                      {% endif %}

                   {% endwith %}
                   <a href="{% url 'logout'%}?next={{request.path}}">Logout</a>
                   {% else %}
                   Your
                   {% with total_items=cart|length %}
                      {% if cart|length > 0 %}
                      <span class="glyphicon glyphicon-shopping-cart"></span>:
                      <a href="{% url 'cart:cart_detail' %}" >
                      {{ total_items }} item{{ total_items|pluralize }}
                      {% else %}
                        <span class="glyphicon glyphicon-shopping-cart"></span> is empty
                      {% endif %}
                    {% endwith %}
                    <a href="{% url 'login'%}?next={{request.path}}">Login/Sign Up</a>
                {% endif %}

              </div>
              <div class="col-sm-7 col-md-7 pull-right">
                  <form class="navbar-form" role="search" method="get" action="{% url 'shop:search' %}" >
                  <div class="input-group">

                      <input type="text" class="form-control" placeholder="Search Products" name="q" required>
                      <div class="input-group-btn">
                          <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                      </div>
                  </div>
                  </form>


              </div>


            </div>



          </ul>

        </div><!--/.nav-collapse -->

      </div>
    </nav>



    <div class="container custom-container" id="midview" style="padding-top:50px; ">
      <div class="row">
        {% block sidebar %}

        {% endblock sidebar %}
        {% block carousel %}

        {% endblock %}
        {% block testimonial %}

        {% endblock %}
      </div>
    </div>
    {% block topseller %}
    {% endblock topseller %}
    {% block recommendations %}
    {% endblock recommendations %}

    <div id="content">
        {% block content %}
        {% endblock %}
    </div>


    </div> <!-- /container -->

<link href="https://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css" rel="stylesheet">

<!--footer start from here-->
<footer>
  <div class="container-fluid" >
    <div class="row bg-primary">
      <div class="col-md-2"></div>
      <div class="col-md-2 col-sm-6 paddingtop-bottom">
        <h6 class="heading7">Contact Us</h6>
        <ul class="footer-ul">
          <li><a href="{% url 'testimonials:testimonial_list' %}"> Consumer Feedback</a></li>
          <li><a href="#"> Complaint Policy</a></li>
          <li><a href="#"> Suppliers / Our Offices</a></li>
          <li><a href="#"> Frequently Ask Questions</a></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-6 paddingtop-bottom">
        <h6 class="heading7">Policies</h6>
        <div class="footer-ul">
          <li><a href="#"> Quality Program</a></li>
          <li><a href="#"> Refund Policy</a></li>
          <li><a href="{% url 'shop:privacy_policy' %}"> Privacy Policy</a></li>
          <li><a href="{% url 'shop:terms_and_conditions' %}"> Terms of Use</a></li>

        </div>
      </div>
      <div class="col-md-5 col-sm-6 paddingtop-bottom">
        <div class="fb-page" data-href="https://www.facebook.com/Himachal-Prisons-127010517681628" data-tabs="timeline" data-height="300" data-small-header="false" style="margin-bottom:15px;" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
          <div class="fb-xfbml-parse-ignore">
            <blockquote cite="https://www.facebook.com/Himachal-Prisons-127010517681628"><a href="https://www.facebook.com/Himachal-Prisons-127010517681628">Facebook</a></blockquote>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
<!--footer start from here-->

<div class="copyright">
  <div class="container">
    <div class="col-md-12">
      <p>© 2016 - All Rights with Himachal Pradesh Prisons & Correctional Services Department.</p>
    </div>
  </div>
</div>



      <!-- facebook share -->
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

      <!-- end facebook share -->

  </body>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</html>

shop/templates/shop/carousel.html
{% load static %}
    <div class="col-md-8 nopadding" style="padding-top:30px;">

            <div id="myCarousel1" class="carousel slide vertical " data-ride="carousel" >
              <!-- Indicators -->
              <ol class="carousel-indicators" style="margin-bottom:-15px;">
                <li data-target="#myCarousel1" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel1" data-slide-to="1"></li>
                <li data-target="#myCarousel1" data-slide-to="2"></li>
                <li data-target="#myCarousel1" data-slide-to="3"></li>
              </ol>

              <!-- Carousel items -->
              <div class="carousel-inner">
                <div class="item active">
                  <img class="center-block img-responsive" src="{% static "img/DSC003160.jpg" %}" style="max-height: 400px;">
                  <div class="carousel-caption" style="margin-bottom:-43px;">

                </div>
                </div>
                <div class="item">
                  <img class="center-block img-responsive" src="{% static "img/DSCN0875.jpg" %}" style="max-height: 400px;">
                  <div class="carousel-caption" style="margin-bottom:-43px;">

                </div>
                </div>
                <div class="item">
                  <img class="center-block img-responsive" src="{% static "img/tailor.jpg" %}" style="max-height: 400px;">
                  <div class="carousel-caption" style="margin-bottom:-43px;">

                </div>
                </div>
                <div class="item">
                  <img class="center-block img-responsive" src="{% static "img/gaeity.jpg" %}" style="max-height: 400px;">
                  <div class="carousel-caption" style="margin-bottom:-43px;">

                </div>
                </div>
              </div>
              <!-- Carousel nav -->
              <a class="carousel-control left " href="#myCarousel1" data-slide="prev">&lsaquo;</a>
              <a class="carousel-control right " href="#myCarousel1" data-slide="next">&rsaquo;</a>
            </div>
    </div>